services:
  translator:
    image: bil-quran/translator
    container_name: bil-quran_translator
    build: .
    volumes:
      - ./models:/app/models:rw
    ports:
      - "8000:8000"
    gpus: all
